id = "viis-theme"
name = "viis"
version = "0.1.0"
schema_version = 1
authors = ["Jack Derksen"]
description = "A nice, muted dark theme with tasteful colours and dimmed comments. Inspired by Monokai Pro."
repository = "https://github.com/JackDerksen/zed-viis"
